service:
  name: ignitecertificate

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: GET
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Properties:
        TableName: users_certificates
        AttributesDefinitions:
          - AttributeName: id
            AttributeType: S
        KeyScheme:
          - AttributeName: id
            KeyType: HASH
